// c program to find and print the nth pell number from the pell series
// Pell numbers are numbers that are similar to the Fibonacci numbers and are generated by the below formula
// Pn=2*Pn-1+Pn-2 with seeds P0=0   P1=1
// First few Pell numbers are 0,1,2,5,12,29,70,169,408,985,2378,5741,13860,33461,...............

#include <stdio.h>
int pell(int n)
{
    int first = 0;
    int second = 1;
    if (n == 1)
    {
        printf("%d\n", first);
        return 0;
    }
    else if (n == 2)
    {
        printf("%d\n", second);
        return 0;
    }
    else
    {
        int third;
        for (int i = 3; i <= n; i++)
        {
            third = 2 * second + first;
            first = second;
            second = third;
        }
        printf("%d\n", third);
    }
    return 0;
}
int main()
{
    int n;
    printf("Enter the number n to print the nth pell number from the pell series\n");
    scanf("%d", &n);
    pell(n);
    return 0;
}

// code by rishavraj1631(github)
// if it helped you just give a star